### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by c-koell** [Eduix/crowd-shibboleth-module#5]
Hi !

I'm currently testing this cool plugin but i don't know how the sync url should look like.

The Sample File says only ...
#New user sync urls for apps
#sync.appname1=url to call with password parameter

Can you give me a example url for confluence and jira please ?

thanks !

**Comment by erkkiaalto** [comment]
sync.nautawiki=https://nautawiki.it.helsinki.fi/rest/syncuser/1.0/sync

**Comment by c-koell** [comment]
Thank you for the comment !

I have looked in the latest doku of the confluence rest api but i can't find the syncuser part ... ?
https://docs.atlassian.com/confluence/REST/latest/

**Comment by erkkiaalto** [comment]
Syncuser is not part of the rest api, it is a separate plugin written by Eduix. Not sure about where the sources are.

**Comment by jmleppala** [comment]
The syncuser plugin is not open source. The good news is that it would seem that if you are using a sufficiently fresh version of Confluence it's not required as the users seem to be getting synced on login. Hopefully this feature will find its way to other Atlassian products as well
